#import <Foundation/Foundation.h>
#import <JSONModel/JSONValueTransformer.h>

/**
* virusapi
* The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


@interface JSONValueTransformer (ISO8601)

@end
