#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* virusapi
* The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMVirusFound.h"
@protocol CMVirusFound;
@class CMVirusFound;



@protocol CMWebsiteScanResult
@end

@interface CMWebsiteScanResult : CMObject

/* True if the scan contained no threats, false otherwise [optional]
 */
@property(nonatomic) NSNumber* cleanResult;
/* Type of threat returned; can be None, Malware, ForcedDownload or Phishing [optional]
 */
@property(nonatomic) NSString* websiteThreatType;
/* Array of viruses found, if any [optional]
 */
@property(nonatomic) NSArray<CMVirusFound>* foundViruses;
/* The remote server URL HTTP reasponse code; useful for debugging issues with scanning; typically if the remote server returns a 200 or 300-series code this means a successful response, while a 400 or 500 series code would represent an error returned from the remote server for the provided URL. [optional]
 */
@property(nonatomic) NSNumber* websiteHttpResponseCode;

@end
